"""v2 economy domain refactor

Revision ID: 073eab95c26b
Revises: e765cafe5452
Create Date: 2026-08-21 18:17:38.348740
"""
from alembic import op
import sqlalchemy as sa


revision = '073eab95c26b'
down_revision = 'e765cafe5452'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_currency_item_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_systems_name'), 'currency_systems', ['name'], unique=True)
    op.create_table('fiat_exchange_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fiat_currency', sa.String(length=8), nullable=False),
    sa.Column('fiat_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['currency_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fiat_exchange_observations_currency_item_id'), 'fiat_exchange_observations', ['currency_item_id'], unique=False)
    op.create_table('item_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_roles_item_id'), 'item_roles', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_roles_role'), 'item_roles', ['role'], unique=False)
    op.create_table('currency_conversion_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_system_id', sa.Integer(), nullable=False),
    sa.Column('from_item_id', sa.Integer(), nullable=False),
    sa.Column('to_item_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['currency_system_id'], ['currency_systems.id'], ),
    sa.ForeignKeyConstraint(['from_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['to_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_conversion_rules_currency_system_id'), 'currency_conversion_rules', ['currency_system_id'], unique=False)
    op.create_index(op.f('ix_currency_conversion_rules_from_item_id'), 'currency_conversion_rules', ['from_item_id'], unique=False)
    op.create_index(op.f('ix_currency_conversion_rules_to_item_id'), 'currency_conversion_rules', ['to_item_id'], unique=False)
    op.create_table('currency_denominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_system_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('base_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['currency_system_id'], ['currency_systems.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_denominations_currency_system_id'), 'currency_denominations', ['currency_system_id'], unique=False)
    op.create_index(op.f('ix_currency_denominations_item_id'), 'currency_denominations', ['item_id'], unique=False)
    op.add_column('activity_records', sa.Column('fiat_value', sa.Numeric(precision=20, scale=8), nullable=True))
    op.alter_column('activity_records', 'duration_minutes',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=4),
               postgresql_using='duration_minutes::numeric',
               existing_nullable=False)
    op.alter_column('activity_records', 'gross_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='gross_value::numeric',
               existing_nullable=False)
    op.alter_column('activity_records', 'total_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='total_cost::numeric',
               existing_nullable=False)
    op.alter_column('activity_records', 'net_profit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='net_profit::numeric',
               existing_nullable=False)
    op.alter_column('activity_records', 'profit_per_hour',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='profit_per_hour::numeric',
               existing_nullable=False)
    op.add_column('dungeon_consumptions', sa.Column('valuation_currency_item_id', sa.Integer(), nullable=True))
    op.add_column('dungeon_consumptions', sa.Column('base_currency_value', sa.Numeric(precision=20, scale=8), nullable=False, server_default='0'))
    op.add_column('dungeon_consumptions', sa.Column('fiat_value', sa.Numeric(precision=20, scale=8), nullable=True))
    op.alter_column('dungeon_consumptions', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='quantity::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_consumptions', 'valuation_unit_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='valuation_unit_price::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_consumptions', 'valuation_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='valuation_total::numeric',
               existing_nullable=False)
    op.create_foreign_key(None, 'dungeon_consumptions', 'items', ['valuation_currency_item_id'], ['id'])
    op.drop_column('dungeon_consumptions', 'valuation_currency')
    op.add_column('dungeon_loots', sa.Column('valuation_currency_item_id', sa.Integer(), nullable=True))
    op.add_column('dungeon_loots', sa.Column('base_currency_value', sa.Numeric(precision=20, scale=8), nullable=False, server_default='0'))
    op.add_column('dungeon_loots', sa.Column('fiat_value', sa.Numeric(precision=20, scale=8), nullable=True))
    op.alter_column('dungeon_loots', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='quantity::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_loots', 'valuation_unit_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='valuation_unit_price::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_loots', 'valuation_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='valuation_total::numeric',
               existing_nullable=False)
    op.create_foreign_key(None, 'dungeon_loots', 'items', ['valuation_currency_item_id'], ['id'])
    op.drop_column('dungeon_loots', 'valuation_currency')
    op.add_column('dungeon_repairs', sa.Column('valuation_unit_price', sa.Numeric(precision=20, scale=8), nullable=False, server_default='0'))
    op.add_column('dungeon_repairs', sa.Column('valuation_currency_item_id', sa.Integer(), nullable=True))
    op.add_column('dungeon_repairs', sa.Column('base_currency_value', sa.Numeric(precision=20, scale=8), nullable=False, server_default='0'))
    op.add_column('dungeon_repairs', sa.Column('fiat_value', sa.Numeric(precision=20, scale=8), nullable=True))
    op.alter_column('dungeon_repairs', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dungeon_repairs', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='quantity::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_repairs', 'material_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='material_cost::numeric',
               existing_nullable=False)
    op.create_index(op.f('ix_dungeon_repairs_item_id'), 'dungeon_repairs', ['item_id'], unique=False)
    op.create_foreign_key(None, 'dungeon_repairs', 'items', ['valuation_currency_item_id'], ['id'])
    op.drop_column('dungeon_repairs', 'currency_cost')
    op.add_column('dungeon_runs', sa.Column('gross_value_fiat', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('dungeon_runs', sa.Column('net_profit_fiat', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('dungeon_runs', sa.Column('profit_per_hour_fiat', sa.Numeric(precision=20, scale=8), nullable=True))
    op.alter_column('dungeon_runs', 'travel_minutes',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=4),
               postgresql_using='travel_minutes::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'combat_minutes',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=4),
               postgresql_using='combat_minutes::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'total_duration_minutes',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=4),
               postgresql_using='total_duration_minutes::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'gross_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='gross_value::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'repair_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='repair_cost::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'consumable_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='consumable_cost::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'other_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='other_cost::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'total_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='total_cost::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'net_profit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='net_profit::numeric',
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'profit_per_hour',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='profit_per_hour::numeric',
               existing_nullable=False)
    op.alter_column('equipment_repair_requirements', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='quantity::numeric',
               existing_nullable=False)
    op.drop_column('equipment_repair_requirements', 'currency_cost')
    op.add_column('item_price_history', sa.Column('currency_item_id', sa.Integer(), nullable=True))
    op.add_column('item_price_history', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('item_price_history', 'price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='price::numeric',
               existing_nullable=False)
    op.alter_column('item_price_history', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='quantity::numeric',
               existing_nullable=True)
    op.create_foreign_key(None, 'item_price_history', 'items', ['currency_item_id'], ['id'])
    op.alter_column('item_relations', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='quantity::numeric',
               existing_nullable=False)
    op.alter_column('items', 'vendor_buy_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='vendor_buy_price::numeric',
               existing_nullable=True)
    op.alter_column('items', 'market_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='market_price::numeric',
               existing_nullable=True)
    op.alter_column('items', 'manual_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='manual_price::numeric',
               existing_nullable=True)
    op.alter_column('items', 'importance_score',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='importance_score::numeric',
               existing_nullable=False)
    op.add_column('production_records', sa.Column('fiat_value', sa.Numeric(precision=20, scale=8), nullable=True))
    op.alter_column('production_records', 'material_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='material_cost::numeric',
               existing_nullable=False)
    op.alter_column('production_records', 'actual_unit_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='actual_unit_cost::numeric',
               existing_nullable=False)
    op.alter_column('production_records', 'revenue',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='revenue::numeric',
               existing_nullable=False)
    op.alter_column('production_records', 'gross_profit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='gross_profit::numeric',
               existing_nullable=False)
    op.alter_column('production_records', 'roi',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='roi::numeric',
               existing_nullable=False)
    op.alter_column('production_records', 'actual_success_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='actual_success_rate::numeric',
               existing_nullable=False)
    op.alter_column('recipe_materials', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='quantity::numeric',
               existing_nullable=False)
    op.alter_column('recipe_outputs', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='quantity::numeric',
               existing_nullable=False)
    op.alter_column('recipes', 'expected_success_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=20, scale=8),
               postgresql_using='expected_success_rate::numeric',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'expected_success_rate',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('recipe_outputs', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('recipe_materials', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('production_records', 'actual_success_rate',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('production_records', 'roi',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('production_records', 'gross_profit',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('production_records', 'revenue',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('production_records', 'actual_unit_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('production_records', 'material_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('production_records', 'fiat_value')
    op.alter_column('items', 'importance_score',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('items', 'manual_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('items', 'market_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('items', 'vendor_buy_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('item_relations', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'item_price_history', type_='foreignkey')
    op.alter_column('item_price_history', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('item_price_history', 'price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('item_price_history', 'notes')
    op.drop_column('item_price_history', 'currency_item_id')
    op.add_column('equipment_repair_requirements', sa.Column('currency_cost', sa.FLOAT(), nullable=False))
    op.alter_column('equipment_repair_requirements', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'profit_per_hour',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'net_profit',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'total_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'other_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'consumable_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'repair_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'gross_value',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'total_duration_minutes',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'combat_minutes',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_runs', 'travel_minutes',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('dungeon_runs', 'profit_per_hour_fiat')
    op.drop_column('dungeon_runs', 'net_profit_fiat')
    op.drop_column('dungeon_runs', 'gross_value_fiat')
    op.add_column('dungeon_repairs', sa.Column('currency_cost', sa.FLOAT(), nullable=False))
    op.drop_constraint(None, 'dungeon_repairs', type_='foreignkey')
    op.drop_index(op.f('ix_dungeon_repairs_item_id'), table_name='dungeon_repairs')
    op.alter_column('dungeon_repairs', 'material_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_repairs', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_repairs', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('dungeon_repairs', 'fiat_value')
    op.drop_column('dungeon_repairs', 'base_currency_value')
    op.drop_column('dungeon_repairs', 'valuation_currency_item_id')
    op.drop_column('dungeon_repairs', 'valuation_unit_price')
    op.add_column('dungeon_loots', sa.Column('valuation_currency', sa.VARCHAR(length=16), nullable=False))
    op.drop_constraint(None, 'dungeon_loots', type_='foreignkey')
    op.alter_column('dungeon_loots', 'valuation_total',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_loots', 'valuation_unit_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_loots', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('dungeon_loots', 'fiat_value')
    op.drop_column('dungeon_loots', 'base_currency_value')
    op.drop_column('dungeon_loots', 'valuation_currency_item_id')
    op.add_column('dungeon_consumptions', sa.Column('valuation_currency', sa.VARCHAR(length=16), nullable=False))
    op.drop_constraint(None, 'dungeon_consumptions', type_='foreignkey')
    op.alter_column('dungeon_consumptions', 'valuation_total',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_consumptions', 'valuation_unit_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('dungeon_consumptions', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('dungeon_consumptions', 'fiat_value')
    op.drop_column('dungeon_consumptions', 'base_currency_value')
    op.drop_column('dungeon_consumptions', 'valuation_currency_item_id')
    op.alter_column('activity_records', 'profit_per_hour',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('activity_records', 'net_profit',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('activity_records', 'total_cost',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('activity_records', 'gross_value',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('activity_records', 'duration_minutes',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('activity_records', 'fiat_value')
    op.drop_index(op.f('ix_currency_denominations_item_id'), table_name='currency_denominations')
    op.drop_index(op.f('ix_currency_denominations_currency_system_id'), table_name='currency_denominations')
    op.drop_table('currency_denominations')
    op.drop_index(op.f('ix_currency_conversion_rules_to_item_id'), table_name='currency_conversion_rules')
    op.drop_index(op.f('ix_currency_conversion_rules_from_item_id'), table_name='currency_conversion_rules')
    op.drop_index(op.f('ix_currency_conversion_rules_currency_system_id'), table_name='currency_conversion_rules')
    op.drop_table('currency_conversion_rules')
    op.drop_index(op.f('ix_item_roles_role'), table_name='item_roles')
    op.drop_index(op.f('ix_item_roles_item_id'), table_name='item_roles')
    op.drop_table('item_roles')
    op.drop_index(op.f('ix_fiat_exchange_observations_currency_item_id'), table_name='fiat_exchange_observations')
    op.drop_table('fiat_exchange_observations')
    op.drop_index(op.f('ix_currency_systems_name'), table_name='currency_systems')
    op.drop_table('currency_systems')
    # ### end Alembic commands ###
