"""initial schema

Revision ID: e765cafe5452
Revises: 
Create Date: 2026-08-21 16:50:50.436437
"""
from alembic import op
import sqlalchemy as sa


revision = 'e765cafe5452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=True)
    op.create_table('dungeons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dungeons_name'), 'dungeons', ['name'], unique=True)
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_name'), 'equipments', ['name'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('rarity', sa.String(length=32), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('stack_size', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('vendor_buy_price', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=True),
    sa.Column('manual_price', sa.Float(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_category'), 'items', ['category'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_success_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=True)
    op.create_table('activity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('gross_value', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('profit_per_hour', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_records_activity_id'), 'activity_records', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_records_activity_type'), 'activity_records', ['activity_type'], unique=False)
    op.create_table('dungeon_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dungeon_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('travel_minutes', sa.Float(), nullable=False),
    sa.Column('combat_minutes', sa.Float(), nullable=False),
    sa.Column('death_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_duration_minutes', sa.Float(), nullable=False),
    sa.Column('gross_value', sa.Float(), nullable=False),
    sa.Column('repair_cost', sa.Float(), nullable=False),
    sa.Column('consumable_cost', sa.Float(), nullable=False),
    sa.Column('other_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('profit_per_hour', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dungeon_id'], ['dungeons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dungeon_runs_dungeon_id'), 'dungeon_runs', ['dungeon_id'], unique=False)
    op.create_table('equipment_repair_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('currency_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_repair_requirements_equipment_id'), 'equipment_repair_requirements', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_repair_requirements_item_id'), 'equipment_repair_requirements', ['item_id'], unique=False)
    op.create_table('item_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('image_type', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_images_file_hash'), 'item_images', ['file_hash'], unique=False)
    op.create_index(op.f('ix_item_images_item_id'), 'item_images', ['item_id'], unique=False)
    op.create_table('item_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price_type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_price_history_item_id'), 'item_price_history', ['item_id'], unique=False)
    op.create_table('item_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_relations_relation_type'), 'item_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_item_relations_source_id'), 'item_relations', ['source_id'], unique=False)
    op.create_index(op.f('ix_item_relations_source_type'), 'item_relations', ['source_type'], unique=False)
    op.create_index(op.f('ix_item_relations_target_item_id'), 'item_relations', ['target_item_id'], unique=False)
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('attempted_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('material_cost', sa.Float(), nullable=False),
    sa.Column('actual_unit_cost', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('gross_profit', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('actual_success_rate', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_records_recipe_id'), 'production_records', ['recipe_id'], unique=False)
    op.create_table('recipe_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_materials_item_id'), 'recipe_materials', ['item_id'], unique=False)
    op.create_index(op.f('ix_recipe_materials_recipe_id'), 'recipe_materials', ['recipe_id'], unique=False)
    op.create_table('recipe_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_outputs_item_id'), 'recipe_outputs', ['item_id'], unique=False)
    op.create_index(op.f('ix_recipe_outputs_recipe_id'), 'recipe_outputs', ['recipe_id'], unique=False)
    op.create_table('dungeon_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dungeon_run_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('valuation_unit_price', sa.Float(), nullable=False),
    sa.Column('valuation_total', sa.Float(), nullable=False),
    sa.Column('valuation_source', sa.String(length=32), nullable=False),
    sa.Column('valuation_currency', sa.String(length=16), nullable=False),
    sa.Column('valuation_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dungeon_run_id'], ['dungeon_runs.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dungeon_consumptions_dungeon_run_id'), 'dungeon_consumptions', ['dungeon_run_id'], unique=False)
    op.create_index(op.f('ix_dungeon_consumptions_item_id'), 'dungeon_consumptions', ['item_id'], unique=False)
    op.create_table('dungeon_loots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dungeon_run_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('valuation_unit_price', sa.Float(), nullable=False),
    sa.Column('valuation_total', sa.Float(), nullable=False),
    sa.Column('valuation_source', sa.String(length=32), nullable=False),
    sa.Column('valuation_currency', sa.String(length=16), nullable=False),
    sa.Column('valuation_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dungeon_run_id'], ['dungeon_runs.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dungeon_loots_dungeon_run_id'), 'dungeon_loots', ['dungeon_run_id'], unique=False)
    op.create_index(op.f('ix_dungeon_loots_item_id'), 'dungeon_loots', ['item_id'], unique=False)
    op.create_table('dungeon_repairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dungeon_run_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('currency_cost', sa.Float(), nullable=False),
    sa.Column('material_cost', sa.Float(), nullable=False),
    sa.Column('valuation_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dungeon_run_id'], ['dungeon_runs.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dungeon_repairs_dungeon_run_id'), 'dungeon_repairs', ['dungeon_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dungeon_repairs_dungeon_run_id'), table_name='dungeon_repairs')
    op.drop_table('dungeon_repairs')
    op.drop_index(op.f('ix_dungeon_loots_item_id'), table_name='dungeon_loots')
    op.drop_index(op.f('ix_dungeon_loots_dungeon_run_id'), table_name='dungeon_loots')
    op.drop_table('dungeon_loots')
    op.drop_index(op.f('ix_dungeon_consumptions_item_id'), table_name='dungeon_consumptions')
    op.drop_index(op.f('ix_dungeon_consumptions_dungeon_run_id'), table_name='dungeon_consumptions')
    op.drop_table('dungeon_consumptions')
    op.drop_index(op.f('ix_recipe_outputs_recipe_id'), table_name='recipe_outputs')
    op.drop_index(op.f('ix_recipe_outputs_item_id'), table_name='recipe_outputs')
    op.drop_table('recipe_outputs')
    op.drop_index(op.f('ix_recipe_materials_recipe_id'), table_name='recipe_materials')
    op.drop_index(op.f('ix_recipe_materials_item_id'), table_name='recipe_materials')
    op.drop_table('recipe_materials')
    op.drop_index(op.f('ix_production_records_recipe_id'), table_name='production_records')
    op.drop_table('production_records')
    op.drop_index(op.f('ix_item_relations_target_item_id'), table_name='item_relations')
    op.drop_index(op.f('ix_item_relations_source_type'), table_name='item_relations')
    op.drop_index(op.f('ix_item_relations_source_id'), table_name='item_relations')
    op.drop_index(op.f('ix_item_relations_relation_type'), table_name='item_relations')
    op.drop_table('item_relations')
    op.drop_index(op.f('ix_item_price_history_item_id'), table_name='item_price_history')
    op.drop_table('item_price_history')
    op.drop_index(op.f('ix_item_images_item_id'), table_name='item_images')
    op.drop_index(op.f('ix_item_images_file_hash'), table_name='item_images')
    op.drop_table('item_images')
    op.drop_index(op.f('ix_equipment_repair_requirements_item_id'), table_name='equipment_repair_requirements')
    op.drop_index(op.f('ix_equipment_repair_requirements_equipment_id'), table_name='equipment_repair_requirements')
    op.drop_table('equipment_repair_requirements')
    op.drop_index(op.f('ix_dungeon_runs_dungeon_id'), table_name='dungeon_runs')
    op.drop_table('dungeon_runs')
    op.drop_index(op.f('ix_activity_records_activity_type'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_activity_id'), table_name='activity_records')
    op.drop_table('activity_records')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_category'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_equipments_name'), table_name='equipments')
    op.drop_table('equipments')
    op.drop_index(op.f('ix_dungeons_name'), table_name='dungeons')
    op.drop_table('dungeons')
    op.drop_index(op.f('ix_activities_name'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
